'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ciudades
    Public Property Id As Integer
    Public Property NombreCiudad As String

    Public Overridable Property Rutas As ICollection(Of Rutas) = New HashSet(Of Rutas)
    Public Overridable Property Rutas1 As ICollection(Of Rutas) = New HashSet(Of Rutas)

End Class
