'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rutas
    Public Property Id As Integer
    Public Property Origen As Integer
    Public Property Destino As Integer
    Public Property Km As Integer
    Public Property Tiempo As System.TimeSpan
    Public Property Precio As Integer

    Public Overridable Property Ciudades As Ciudades
    Public Overridable Property Ciudades1 As Ciudades

End Class
